# Generated by Django 4.1.6 on 2023-03-13 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.DateTimeField(auto_now_add=True)),
                ('atualização', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.DateTimeField(auto_now_add=True)),
                ('atualização', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cep', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('numero', models.IntegerField(max_length=200)),
                ('cidade', models.CharField(default='0', max_length=100, verbose_name=[('teste', 'ts')])),
                ('estado', models.CharField(default='0', max_length=100, verbose_name=[('teste', 'ts')])),
                ('complemento', models.CharField(max_length=70)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.DateTimeField(auto_now_add=True)),
                ('atualização', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('foto', stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='path/to/img', variations={}, verbose_name='foto')),
                ('encomendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correios.encomenda')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correios.endereco')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
