# Generated by Django 4.1.6 on 2023-03-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correios', '0003_alter_endereco_cidade_alter_endereco_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
