# Generated by Django 4.1.6 on 2023-03-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correios', '0004_alter_endereco_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(choices=[('', '---------')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('', '---------')], default='', max_length=100),
        ),
    ]
