# Generated by Django 4.1.6 on 2023-03-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correios', '0005_alter_endereco_cidade_alter_endereco_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='encomendas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='correios.encomenda'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='correios.endereco'),
        ),
    ]
