# Generated by Django 4.1.6 on 2023-03-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correios', '0006_alter_usuario_encomendas_alter_usuario_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='encomendas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='encomendas',
            field=models.ManyToManyField(null=True, to='correios.encomenda'),
        ),
    ]
