# Generated by Django 4.1.6 on 2023-03-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correios', '0007_remove_usuario_encomendas_usuario_encomendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.ManyToManyField(null=True, to='correios.endereco'),
        ),
    ]
